### ISSUE TITLE
When a user sets `testsPositive`, trigger the firebase HTTPS callable function to notify

### ISSUE THREAD

**Issue by mmmoli** [ContactTracing-app/Frontend#9]
# What
The whole point of the app is to notify your friends and family when you status changes. We've stored this log of contact in a graph to make it easier to find friends-of-friends and keep them up-to-date.

This ticket is to create the necessary UI to make this functionality real.

# Flow
1. User visits `ProfileView`
1. User sets `testsPositive` to true
1. Call Firebase "HTTPS Callable" Firebase Function, to make two requests to the API:
    a: RecentDirectContacts
    b: RecentIndrectContacts
1. Direct Contacts get urgent notifications based on their notification preferences
1. Direct Contacts get less urgent notifications based on their notification preferences

# Tasks
- [ ] Build UI to collect status (#16 )
- [ ] Commit the preference to Firestore
- [x] Create [Firebase Function Callable](https://github.com/ContactTracing-app/Firebase-Functions) to make API requests.
- [ ] Build templates of messages

**Comment by kavyvetri** [comment]
5. **In**Direct Contacts get less urgent notifications based on their notification preferences

**Comment by pongponk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When a user sets `testsPositive`, trigger the firebase HTTPS callable function to notify](https://trello.com/c/yTlvXjXe/11-when-a-user-sets-testspositive-trigger-the-firebase-https-callable-function-to-notify)

**Comment by mmmoli** [comment]
@maxzitron I've deployed the Firebase Functions with https://github.com/ContactTracing-app/Firebase-Functions/pull/3.

From the frontend, the call Signature you want is:
```
interface SendNotifications {
    uid: string
}
sendNotifications(data: SendNotifications)
```

It's a bit odd how we do this now. See [`withFunctions` hook](https://github.com/ContactTracing-app/Frontend/blob/master/src/hooks/useFunctions.ts)

**Comment by magfurulabeer** [comment]
I'll try to tackle this one

**Comment by mmmoli** [comment]
Agreed spec for the UI:

Dropdown with 3 options:
- "I'm totally fine" (default)
- "show symptoms"
- "Confirmed positive"

Separate switch: "in quarantine" boolean

**Comment by firacloudtech** [comment]
I'll work on this.
